# -*- coding: utf-8 -*-
"""Carrinho de Compras

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFhUZsDGwvdf0jXo9Vt1uyY128P_ELjx
"""

carrinho = []

print("=== Sistema de Carrinho de Compras ===")

while True:
    print("\n1 - Adicionar item ao carrinho")
    print("2 - Remover último item")
    print("3 - Mostrar carrinho")
    print("0 - Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == '1':
        produto = input("Nome do produto: ")
        quantidade = int(input("Quantidade: "))
        preco = float(input("Preço unitário: R$ "))
        carrinho.append([produto, quantidade, preco])
        print(f"{produto} adicionado ao carrinho.")

    elif opcao == '2':
        if carrinho:
            removido = carrinho.pop()
            print(f"Produto removido: {removido[0]}")
        else:
            print("Carrinho vazio, nada para remover.")

    elif opcao == '3':
        if not carrinho:
            print("Carrinho vazio.")
        else:
            print("\nCarrinho de compras:")
            print("Produto       Quantidade    Preço Unitário    Total")
            total_geral = 0
            for item in carrinho:
                produto, quantidade, preco = item
                total = quantidade * preco
                total_geral += total
                print(f"{produto:<13} {quantidade:<12} R${preco:<15.2f} R${total:.2f}")
            print(f"\nTotal geral: R${total_geral:.2f}")

    elif opcao == '0':
        break

    else:
        print("Opção inválida. Tente novamente.")

print("\nObrigado por usar o carrinho de compras!")