# -*- coding: utf-8 -*-
"""Carrinho de Compras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w248NBf-qewkD1Pxq9A5m-2Mee7S6lu3
"""

print("\n== CARRINHO DE COMPRAS ==")
carrinho = []

while True:
    acao = input("Digite 'add', 'ver' ou 'sair': ").lower()
    if acao == 'add':
        nome = input("Produto: ")
        qtd = int(input("Quantidade: "))
        preco = float(input("Preço por unidade: "))
        carrinho.append([nome, qtd, preco])
    elif acao == 'ver':
        total = 0
        print("Itens no carrinho:")
        for item in carrinho:
            print(f"{item[1]}x {item[0]} - R${item[2]:.2f} cada")
            total += item[1] * item[2]
        print(f"Total a pagar: R${total:.2f}")
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.")