# -*- coding: utf-8 -*-
"""DadosUsuáriosLogados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFzeHslH0uj260UVPJAhyGn3bzaxhVKN
"""

print("\n== DADOS DE USUÁRIOS LOGADOS ==")
fila_usuarios_logados = deque()

# Simulando login de vários usuários
while True:
    acao = input("Digite 'logar', 'ver fila' ou 'sair': ").lower()
    if acao == 'logar':
        nome = input("Nome do usuário: ")
        email = input("Email: ")
        senha = input("Senha: ")
        usuario = {"nome": nome, "email": email, "senha": senha}
        fila_usuarios_logados.append(usuario)
        print(f"{nome} foi adicionado à fila de usuários logados.\n")
    elif acao == 'ver fila':
        if fila_usuarios_logados:
            print("Usuários na fila de login (ordem de entrada):")
            for u in fila_usuarios_logados:
                print(f"- {u['nome']} | {u['email']}")
        else:
            print("Nenhum usuário logado ainda.\n")
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.")