# -*- coding: utf-8 -*-
"""Lista de produtosipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFzeHslH0uj260UVPJAhyGn3bzaxhVKN
"""

print("\n== LISTA DE COMPRAS ==")
lista_compras = []

while True:
    acao = input("Digite 'add', 'remover', 'ver' ou 'sair': ").lower()
    if acao == 'add':
        produto = input("Nome do produto: ")
        lista_compras.append(produto)
    elif acao == 'remover':
        produto = input("Produto para remover: ")
        if produto in lista_compras:
            lista_compras.remove(produto)
        else:
            print("Produto não encontrado.")
    elif acao == 'ver':
        print("Lista de compras:")
        for item in lista_compras:
            print("-", item)
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.")