# -*- coding: utf-8 -*-
"""listaprodutos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXta30K3SlYj8D4uAFFi7SGgx_WH_qaT
"""

class ProdutoTransporte:
    pass

ProdutoTransporte.__init__ = lambda self, codigo, nome, categoria, preco: (
    setattr(self, 'codigo', codigo),
    setattr(self, 'nome', nome),
    setattr(self, 'categoria', categoria),
    setattr(self, 'preco', preco)
)

ProdutoTransporte.__str__ = lambda self: (
    f"Código: {self.codigo} | Nome: {self.nome} | "
    f"Categoria: {self.categoria} | Preço: R$ {self.preco:.2f}"
)

class EstoqueTransporte:
    pass

EstoqueTransporte.__init__ = lambda self: setattr(self, 'produtos', [])

estoque = EstoqueTransporte()

while True:
    print("\n1. Adicionar produto")
    print("2. Listar produtos")
    print("3. Buscar produto")
    print("4. Sair")
    escolha = input("Escolha uma opção: ")

    if escolha == "1":
        codigo = input("Digite o código do produto: ")
        if any(p.codigo == codigo for p in estoque.produtos):
            print("Produto com este código já existe!")
            continue

        nome = input("Digite o nome do produto: ")
        categoria = input("Digite a categoria (Peça, Serviço, Equipamento): ")
        try:
            preco = float(input("Digite o preço do produto: "))
        except ValueError:
            print("Preço inválido!")
            continue

        produto = ProdutoTransporte(codigo, nome, categoria, preco)
        estoque.produtos.append(produto)
        print("Produto adicionado com sucesso!")

    elif escolha == "2":
        if not estoque.produtos:
            print("Nenhum produto cadastrado.")
            continue

        print("\nLista de Produtos da Área de Transportes:")
        for produto in estoque.produtos:
            print(produto)

    elif escolha == "3":
        codigo = input("Digite o código do produto para buscar: ")
        encontrado = False
        for produto in estoque.produtos:
            if produto.codigo == codigo:
                print("Produto encontrado:")
                print(produto)
                encontrado = True
                break
        if not encontrado:
            print("Produto não encontrado.")

    elif escolha == "4":
        print("Encerrando o programa.")
        break

    else:
        print("Opção inválida. Tente novamente.")