# -*- coding: utf-8 -*-
"""Max33 E-Commerce Tradicional de Transporte

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFhUZsDGwvdf0jXo9Vt1uyY128P_ELjx
"""

from collections import deque


print("== LOGIN / LOGOUT ==")
pilha_login = []

while True:
    acao = input("Digite 'login', 'logout' ou 'sair': ").lower()
    if acao == 'login':
        nome = input("Digite o nome de usuário: ")
        email = input("Digite o email: ")
        senha = input("Digite a senha: ")
        usuario = {"nome": nome, "email": email, "senha": senha}
        pilha_login.append(usuario)
        print("Login realizado com sucesso.\n")
    elif acao == 'logout':
        if pilha_login:
            saiu = pilha_login.pop()
            print(f"{saiu['nome']} fez logout.\n")
        else:
            print("Nenhum usuário logado.\n")
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.\n")

print("\n== LISTA DE COMPRAS ==")
lista_compras = []

while True:
    acao = input("Digite 'add', 'remover', 'ver' ou 'sair': ").lower()
    if acao == 'add':
        produto = input("Nome do produto: ")
        lista_compras.append(produto)
    elif acao == 'remover':
        produto = input("Produto para remover: ")
        if produto in lista_compras:
            lista_compras.remove(produto)
        else:
            print("Produto não encontrado.")
    elif acao == 'ver':
        print("Lista de compras:")
        for item in lista_compras:
            print("-", item)
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.")


print("\n== CARRINHO DE COMPRAS ==")
carrinho = []

while True:
    acao = input("Digite 'add', 'ver' ou 'sair': ").lower()
    if acao == 'add':
        nome = input("Produto: ")
        qtd = int(input("Quantidade: "))
        preco = float(input("Preço por unidade: "))
        carrinho.append([nome, qtd, preco])
    elif acao == 'ver':
        total = 0
        print("Itens no carrinho:")
        for item in carrinho:
            print(f"{item[1]}x {item[0]} - R${item[2]:.2f} cada")
            total += item[1] * item[2]
        print(f"Total a pagar: R${total:.2f}")
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.")


print("\n== MÉTODOS DE PAGAMENTO ==")
pagamentos = [
    ["Cartão de Crédito", 3.5, 12],
    ["PIX", 0.0, 1],
    ["Boleto", 1.2, 1]
]

print("Opções de pagamento disponíveis:")
for metodo in pagamentos:
    print(f"{metodo[0]} - Taxa: {metodo[1]}% - até {metodo[2]}x")


print("\n== DADOS DE USUÁRIOS LOGADOS ==")
fila_usuarios_logados = deque()

while True:
    acao = input("Digite 'logar', 'ver fila' ou 'sair': ").lower()
    if acao == 'logar':
        nome = input("Nome do usuário: ")
        email = input("Email: ")
        senha = input("Senha: ")
        usuario = {"nome": nome, "email": email, "senha": senha}
        fila_usuarios_logados.append(usuario)
        print(f"{nome} foi adicionado à fila de usuários logados.\n")
    elif acao == 'ver fila':
        if fila_usuarios_logados:
            print("Usuários na fila de login (ordem de entrada):")
            for u in fila_usuarios_logados:
                print(f"- {u['nome']} | {u['email']}")
        else:
            print("Nenhum usuário logado ainda.\n")
    elif acao == 'sair':
        break
    else:
        print("Comando inválido.")