# -*- coding: utf-8 -*-
"""Métodos de pagamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSPzA59ossPCeuPH49Psaw80pOsvdd-L
"""

print("\n== MÉTODOS DE PAGAMENTO ==")
pagamentos = [
    ["Cartão de Crédito", 3.5, 12],
    ["PIX", 0.0, 1],
    ["Boleto", 1.2, 1]
]

print("Opções de pagamento disponíveis:")
for metodo in pagamentos:
    print(f"{metodo[0]} - Taxa: {metodo[1]}% - até {metodo[2]}x")