# -*- coding: utf-8 -*-
"""Métodos de pagamentos(Nova Branch).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1INv07zXzpKDP4rpN16MsAk2te73bMCPD
"""

print("\n== MÉTODOS DE PAGAMENTO ==")
pagamentos = [
    ["Cartão de Crédito", 3.5, 12],
    ["PIX", 0.0, 1],
    ["Boleto", 1.2, 1]
]

print("Opções de pagamento disponíveis:")
for i, metodo in enumerate(pagamentos, start=1):
    print(f"{i} - {metodo[0]} - Taxa: {metodo[1]}% - até {metodo[2]}x")

escolha = int(input("Coloque o método de pagamento: 1=Cartão de Crédito, 2=PIX, 3=Boleto: "))

if escolha == 1:
    taxa = pagamentos[0][1]
    max_parcelas = pagamentos[0][2]
    parcela = int(input(f'A taxa será de {taxa}%. Quantas parcelas (até {max_parcelas})? '))
    if parcela <= max_parcelas:
        print(f'Será efetuado em {parcela}x com taxa de {taxa}%')
    else:
        print('Erro: número de parcelas excede o máximo permitido.')
elif escolha == 2:
    print('Pagamento via PIX: sem taxa e sem parcelamento.')
elif escolha == 3:
    taxa = pagamentos[2][1]
    print(f'Pagamento via Boleto com taxa de {taxa}%. Sem parcelamento.')
else:
    print('Erro: método de pagamento inválido.')