# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeTXD1BdqU2s-g5QmqthDltWfahG66-D
"""

usuarios = []
logados = []


print("=== Cadastro de Usuários ===")
while True:
    nome = input("Digite o nome de usuário (ou 'sair' para terminar): ")
    if nome == 'sair':

senha = input(f"Digite a senha para {nome}: ")
usuarios.append({'usuario': nome, 'senha': senha})


usuario = input("\nDigite seu nome de usuário para login: ")
senha = input("Digite sua senha: ")

if any(u['usuario'] == usuario and u['senha'] == senha for u in usuarios):
    if usuario not in logados:
        logados.append(usuario)
        print(f"{usuario} logado com sucesso.")
    else:
        print(f"{usuario} já está logado.")
else:
    print("Usuário ou senha incorretos.")


print("\nUsuários logados:", ", ".join(logados) if logados else "Nenhum usuário logado.")


if input("\nDeseja deslogar? (s/n): ").lower() == 's':
    logout = input("Digite o nome do usuário para deslogar: ")
    if logout in logados:
        logados.remove(logout)
        print(f"{logout} deslogado com sucesso.")
    else:
        print(f"{logout} não está logado.")

    print("\nUsuários logados após o logout:", ", ".join(logados) if logados else "Nenhum usuário logado.")

usuarios = []
logados = []

# Cadastro de Usuários
print("=== Cadastro de Usuários ===")
while True:
    print("\nOpções disponíveis:")
    print("1. Cadastrar novo usuário")
    print("2. Remover usuário")
    print("3. Finalizar cadastro")

    opcao = input("Escolha uma opção (1, 2 ou 3): ")

    if opcao == '1':  # Cadastrar novo usuário
        nome = input("Digite o nome de usuário: ")
        senha = input(f"Digite a senha para {nome}: ")
        usuarios.append({'usuario': nome, 'senha': senha})
        print(f"Usuário {nome} cadastrado com sucesso.")

    elif opcao == '2':  # Remover usuário
        nome = input("Digite o nome do usuário a ser removido: ")
        usuarios = [u for u in usuarios if u['usuario'] != nome]  # Remove o usuário
        print(f"Usuário {nome} removido, se existia.")

    elif opcao == '3':  # Finalizar cadastro
        continuar = input("Tem certeza que deseja finalizar o cadastro? (s/n): ").strip().lower()
        if continuar == 's':
            break  # Sai do loop apenas quando o usuário confirmar

    else:
        print("Opção inválida, por favor, escolha 1, 2 ou 3.")

# Login
usuario = input("\nDigite seu nome de usuário para login: ")
senha = input("Digite sua senha: ")

# Verificação de login
if any(u['usuario'] == usuario and u['senha'] == senha for u in usuarios):
    if usuario not in logados:
        logados.append(usuario)
        print(f"{usuario} logado com sucesso.")
    else:
        print(f"{usuario} já está logado.")
else:
    print("Usuário ou senha incorretos.")

# Exibição de usuários logados
print("\nUsuários logados:", ", ".join(logados) if logados else "Nenhum usuário logado.")

# Logout
if input("\nDeseja deslogar? (s/n): ").lower() == 's':
    logout = input("Digite o nome do usuário para deslogar: ")
    if logout in logados:
        logados.remove(logout)
        print(f"{logout} deslogado com sucesso.")
    else:
        print(f"{logout} não está logado.")

    # Exibindo usuários logados após o logout
    print("\nUsuários logados após o logout:", ", ".join(logados) if logados else "Nenhum usuário logado.")

usuarios = []
logados = []

while True:
    opcao = input("\n1. Cadastrar\n2. Remover\n3. Finalizar\nEscolha: ")

    if opcao == '1':
        usuarios.append({'usuario': input("Nome: "), 'senha': input("Senha: ")})
        print("Cadastrado.")

    elif opcao == '2':
        nome = input("Usuário a remover: ")
        usuarios = [u for u in usuarios if u['usuario'] != nome]
        print("Removido.")

    elif opcao == '3':
        if input("Finalizar cadastro? (s/n): ").lower() == 's':
            break
    else:
        print("Opção inválida.")


usuario = input("\nUsuário para login: ")
senha = input("Senha: ")

if any(u['usuario'] == usuario and u['senha'] == senha for u in usuarios):
    if usuario not in logados:
        logados.append(usuario)
        print(f"{usuario} logado.")
    else:
        print(f"{usuario} já está logado.")
else:
    print("Erro de login.")


print("\nLogados:", ", ".join(logados) if logados else "Nenhum logado.")


if input("\nDeslogar? (s/n): ").lower() == 's':
    logout = input("Usuário para deslogar: ")
    if logout in logados:
        logados.remove(logout)
        print(f"{logout} deslogado.")
    else:
        print(f"{logout} não está logado.")

    print("Logados após logout:", ", ".join(logados) if logados else "Nenhum logado.")