#teste

# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeTXD1BdqU2s-g5QmqthDltWfahG66-D
"""

usuarios = []
logados = []

while True:
    opcao = input("\n1. Cadastrar\n2. Remover\n3. Finalizar\nEscolha: ")

    if opcao == '1':
        usuarios.append({'usuario': input("Nome: "), 'senha': input("Senha: ")})
        print("Cadastrado.")

    elif opcao == '2':
        nome = input("Usuário a remover: ")
        usuarios = [u for u in usuarios if u['usuario'] != nome]
        print("Removido.")

    elif opcao == '3':
        if input("Finalizar cadastro? (s/n): ").lower() == 's':
            break
    else:
        print("Opção inválida.")


usuario = input("\nUsuário para login: ")
senha = input("Senha: ")

if any(u['usuario'] == usuario and u['senha'] == senha for u in usuarios):
    if usuario not in logados:
        logados.append(usuario)
        print(f"{usuario} logado.")
    else:
        print(f"{usuario} já está logado.")
else:
    print("Erro de login.")


print("\nLogados:", ", ".join(logados) if logados else "Nenhum logado.")


if input("\nDeslogar? (s/n): ").lower() == 's':
    logout = input("Usuário para deslogar: ")
    if logout in logados:
        logados.remove(logout)
        print(f"{logout} deslogado.")
    else:
        print(f"{logout} não está logado.")

    print("Logados após logout:", ", ".join(logados) if logados else "Nenhum logado.")
