# -*- coding: utf-8 -*-
"""UsuáriosLogados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFzeHslH0uj260UVPJAhyGn3bzaxhVKN
"""

print("\n== DADOS DO USUÁRIO LOGADO ==")
if pilha_login:
    usuario_atual = pilha_login[-1]  # O último que fez login
    print(f"Usuário atual: {usuario_atual['nome']}")
    print(f"E-mail: {usuario_atual['email']}")
else:
    print("Nenhum usuário está logado no momento.")